version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_filament_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel_network

  web:
    image: nginx:alpine
    container_name: laravel_filament_web
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network

  db:
    image: mysql:8.0
    container_name: laravel_filament_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pss
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

volumes:
  db_data:

networks:
  laravel_network:
    driver: bridge
